
const { body } = require('express-validator');

module.exports = {

    addCropValidator : [
        
        body('user_id').isString(),
        body('title').isString(),
        body('type').isString(),
        body('category_id').isString(),
        body('subcategory_id').isString(),
        // body('active').isString(),
        // body('market').isString(),
        body('description').isString(),
        // body('images').isString(),
        body('currency').isString(),
        body('is_negotiable').isString(),
        body('video').isString(),
        body('packaging').isString(),
        body('application').isString(),
        // body('manufacture_name').isString(),
        // body('manufacture_date').isString(),
        // body('expiration_date').isString(),

        body('model_type').isString(),
        body('qty').isString(),
        body('price').isString(),
        body('color').isString(),
        body('moisture').isString(),
        body('foreign_matter').isString(),
        body('broken_grains').isString(),
        body('weevil').isString(),
        body('dk').isString(),
        body('rotten_shriveled').isString(),
        body('test_weight').isString(),
        body('hectoliter').isString(),
        body('hardness').isString(),
        body('splits').isString(),
        body('oil_content').isString(),
        body('infestation').isString(),
        body('grain_size').isString(),
        body('total_defects').isString(),
        body('dockage').isString(),
        body('ash_content').isString(),
        body('acid_ash').isString(),
        body('volatile').isString(),
        body('mold').isString(),
        body('drying_process').isString(),
        body('dead_insect').isString(),
        body('mammalian').isString(),
        body('infested_by_weight').isString(),
        body('curcumin_content').isString(),
        body('extraneous').isString(),
        body('unit').isString(),
        // body('kg').isString(),
        // body('liters').isString()

        // body('crop_id').isString(),
        body('state').isString(),
        body('zip').isString(),
        body('country').isString(),
        body('address').isString(),
        body('delivery_window').isString()
    ],
}